# Generated by Django 5.0.4 on 2024-05-10 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(default='Produto', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('posicao', models.CharField(choices=[('Avançado', 'Avançado'), ('Extremo', 'Extremo'), ('Médio', 'Médio'), ('Central', 'Central'), ('Lateral', 'Lateral'), ('Guarda-Redes', 'Guarda-Redes')], max_length=20)),
                ('idade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adversario', models.CharField(max_length=50)),
                ('golos_clube', models.PositiveIntegerField()),
                ('golos_adversario', models.PositiveIntegerField()),
                ('local', models.CharField(choices=[('fora', 'Fora'), ('casa', 'Casa')], max_length=10)),
                ('data_jogo', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('descricao', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='clubehome/static/noticias/')),
                ('data_publicacao', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bilhete',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clubehome.produto')),
                ('data', models.DateField()),
                ('lugar', models.IntegerField()),
                ('N_Emissao', models.IntegerField()),
            ],
            bases=('clubehome.produto',),
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_socio', models.BooleanField(default=False)),
                ('NIF', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubehome.produto')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubehome.userdetails')),
            ],
        ),
    ]
