# Generated by Django 5.0.4 on 2024-05-08 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubehome', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='conta_ptr',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='utilizador_ptr',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='utilizador',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='produto',
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_socio', models.BooleanField(default=False)),
                ('NIF', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Conta',
        ),
        migrations.DeleteModel(
            name='Socio',
        ),
        migrations.DeleteModel(
            name='Utilizador',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
