# Generated by Django 5.0.4 on 2024-05-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubehome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagem_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
