# Generated by Django 5.0.4 on 2024-05-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubehome', '0002_coach_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jogador',
        ),
    ]
