# Generated by Django 5.0.4 on 2024-05-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubehome', '0002_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='carrinho',
        ),
        migrations.AddField(
            model_name='venda',
            name='produtos',
            field=models.ManyToManyField(to='clubehome.product'),
        ),
    ]
