# Generated by Django 5.0.4 on 2024-05-12 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubehome', '0002_noticia_imagem_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilhete',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clubehome.product')),
                ('equipa_fora', models.CharField(max_length=255)),
                ('equipa_casa', models.CharField(max_length=255)),
                ('data', models.DateField()),
            ],
            bases=('clubehome.product',),
        ),
    ]
