# Generated by Django 5.0.4 on 2024-05-08 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubehome', '0002_remove_utilizador_conta_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubehome.produto')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubehome.userdetails')),
            ],
        ),
    ]
