# Generated by Django 5.0.4 on 2024-05-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubehome', '0003_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('descricao', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='siteclube/clubehome/static/noticias/')),
                ('data_publicacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
