# Generated by Django 5.0.4 on 2024-05-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubehome', '0003_delete_jogador'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default='clubehome/static/logo.png', upload_to='clubehome/static/produtos'),
        ),
    ]
