# Generated by Django 5.0.4 on 2024-05-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubehome', '0004_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adversario', models.CharField(max_length=50)),
                ('golos_clube', models.PositiveIntegerField()),
                ('golos_adversario', models.PositiveIntegerField()),
                ('local', models.CharField(choices=[('fora', 'Fora'), ('casa', 'Casa')], max_length=10)),
                ('data_jogo', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(upload_to='clubehome/static/noticias/'),
        ),
    ]
