# Generated by Django 5.0.4 on 2024-05-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubehome', '0004_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='type',
            field=models.CharField(default='Produto', max_length=100),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(upload_to='clubehome/static/noticias/'),
        ),
        migrations.DeleteModel(
            name='Merchandising',
        ),
    ]
