# Generated by Django 5.0.4 on 2024-05-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubehome', '0004_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='clubehome/static/produtos/'),
        ),
    ]
