# Generated by Django 5.0.4 on 2024-05-09 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubehome', '0005_produto_tipo_alter_noticia_imagem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='type',
            new_name='type',
        ),
    ]
