# Generated by Django 5.0.4 on 2024-05-10 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubehome', '0005_alter_produto_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='imagem',
            new_name='imag',
        ),
    ]
