# Generated by Django 5.0.4 on 2024-05-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubehome', '0006_rename_imagem_produto_imag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Bilhete',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
