# Generated by Django 5.0.4 on 2024-05-09 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubehome', '0005_jogo_alter_noticia_imagem'),
        ('clubehome', '0006_rename_tipo_produto_type'),
    ]

    operations = [
    ]
