# Generated by Django 5.0.4 on 2024-05-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubehome', '0006_rename_tipo_produto_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='ID_prod',
        ),
    ]
