# Generated by Django 5.0.4 on 2024-05-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubehome', '0007_remove_venda_produto_delete_bilhete_delete_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(default='Produto', max_length=100)),
                ('imagem', models.ImageField(upload_to='clubehome/static/imagens/')),
                ('preco', models.IntegerField(default=0)),
            ],
        ),
    ]
