# Generated by Django 5.0.4 on 2024-05-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubehome', '0007_merge_20240509_1451'),
        ('clubehome', '0007_remove_produto_id_prod'),
    ]

    operations = [
    ]
