# Generated by Django 5.0.4 on 2024-05-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubehome', '0008_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagem',
            field=models.ImageField(default='clubehome/static/logo.png', upload_to='clubehome/static/imagens/'),
        ),
    ]
