# Generated by Django 5.0.4 on 2024-05-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubehome', '0009_alter_product_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='clubehome/static/imagens/'),
        ),
    ]
