# Generated by Django 5.0.4 on 2024-05-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubehome', '0012_carrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cod_produto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
